from penflow.agents.protocol.cache_poisoning_agent import WebCachePoisoningCapabilityAgent
from penflow.agents.protocol.cl0_smuggling_agent import CL0SmugglingCapabilityAgent
from penflow.agents.protocol.cors_agent import CORSCapabilityAgent
from penflow.agents.protocol.framework_cache_poisoning_agent import FrameworkCachePoisoningAgent
from penflow.agents.protocol.http2_connect_agent import HTTP2ConnectCapabilityAgent
from penflow.agents.protocol.http_smuggling_agent import HTTPSmugglingCapabilityAgent
from penflow.agents.protocol.multipart_parser_bypass_agent import MultipartParserBypassCapabilityAgent
from penflow.agents.protocol.websocket_agent import WebSocketCapabilityAgent
