from typing import List, Optional
from penflow.planning.hypothesis import Hypothesis
from penflow.planning.planning_rules import PlanningRuleEngine
from penflow.planning.reasoning import ReasoningEngine

class HypothesisBuilder:
    """
    Builds structured, explainable hypotheses from reconnaissance observations.
    """
    def __init__(self, rule_engine: Optional[PlanningRuleEngine] = None):
        self.rule_engine = rule_engine or PlanningRuleEngine()
        self.reasoning = ReasoningEngine()

    def build_from_observation(self, observation_text: str) -> List[Hypothesis]:
        matched_rules = self.rule_engine.evaluate(observation_text)
        hypotheses = []

        for rule in matched_rules:
            reason_chain = self.reasoning.build_reasoning_chain(
                observations=[observation_text],
                condition_logic=rule.generated_reason,
                conclusion=rule.generated_title
            )
            h = Hypothesis(
                title=rule.generated_title,
                description=f"Automated hypothesis generated by rule {rule.rule_id}",
                reason=reason_chain,
                confidence=0.5,
                priority=5.0,
                required_capabilities=rule.required_capabilities,
                required_observations=[observation_text]
            )
            hypotheses.append(h)

        return hypotheses
